# Site settings
title-bold: ThanhCS94
title-normal: Mobile developer
email: nguyenvanthanh9294@gmail.com
description: Currently, I'm investing my time into learning about mobile development.</br>How I ended up on this path is a long story.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://andrewbanchich.gitlab.io" # the base hostname & protocol for your site
author:
street_address: Ly Thuong Kiet
city: Ho Chi Minh
state: VN
zip_code: 700000
country: Viet Nam
phone: (+84) 1626741286

# Plugins

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
